// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV1laIt-MaakWc9Qr8Pu3fXe4249i8uzo',
    appId: '1:692144165649:web:91186fbffae938f3a0b2b0',
    messagingSenderId: '692144165649',
    projectId: 'eshop-multivendor',
    authDomain: 'eshop-multivendor.firebaseapp.com',
    storageBucket: 'eshop-multivendor.appspot.com',
    measurementId: 'G-3KRYGZJPMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7F5pGTk1Yqwj5_ayYsVBcFtVyx29C0MM',
    appId: '1:692144165649:android:6fc2795776be996fa0b2b0',
    messagingSenderId: '692144165649',
    projectId: 'eshop-multivendor',
    storageBucket: 'eshop-multivendor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyo2eRQcgSmf6-cljpz14ZqDbHwX34x0A',
    appId: '1:692144165649:ios:10f6966981e64317a0b2b0',
    messagingSenderId: '692144165649',
    projectId: 'eshop-multivendor',
    storageBucket: 'eshop-multivendor.appspot.com',
    androidClientId:
        '692144165649-1g138475mvblralj5bqfshev5rlh3bag.apps.googleusercontent.com',
    iosClientId:
        '692144165649-snblmkb8k3eha5uc8019ncj51uk9gb0m.apps.googleusercontent.com',
    iosBundleId: 'eshop.seller.multivendor',
  );
}
